--CREATE TABLE "productos" ("id"INTEGER,"nombre_producto"TEXT,"precio"REAL,"stock_disponible"NUMERIC,PRIMARY KEY("id" AUTOINCREMENT))
INSERT INTO "productos"("nombre_producto","precio","stock_disponible")
--VALUES("tequila",100000,30)
--VALUES("vodka",90000,40)
--VALUES("ginebra",180000,20)